"""Шаблон для автогенерации миграций Alembic.

Ревизия: ac0841f5b1fd
Создана: 2026-02-20 10:55:47.289491
Сообщение: создание таблиц clients и operations
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Идентификаторы ревизии (используются Alembic)
revision: str = 'ac0841f5b1fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применить миграцию (вперёд)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False, comment='Имя пользователя в RemnaWave'),
    sa.Column('remnawave_uuid', sa.String(length=255), nullable=True, comment='UUID пользователя на стороне RemnaWave'),
    sa.Column('short_uuid', sa.String(length=255), nullable=True, comment='Короткий UUID подписки (из RemnaWave)'),
    sa.Column('subscription_url', sa.String(length=1024), nullable=True, comment='URL подписки клиента'),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', name='client_status', create_constraint=True), nullable=False, comment='Статус клиента: active / blocked'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Дата истечения подписки'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remnawave_uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False, comment='Ссылка на клиента'),
    sa.Column('action', sa.Enum('CREATE', 'DELETE', 'EXTEND', 'BLOCK', 'UNBLOCK', 'GET_CONFIG', 'ROTATE_CONFIG', 'AUTO_DEACTIVATE', name='action_type', create_constraint=True), nullable=False, comment='Тип операции'),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Входные данные операции (JSON)'),
    sa.Column('result', sa.Enum('SUCCESS', 'FAIL', name='operation_result', create_constraint=True), nullable=False, comment='Результат: success / fail'),
    sa.Column('error', sa.Text(), nullable=True, comment='Текст ошибки (при fail)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_client_id'), 'operations', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатить миграцию (назад)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_client_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_table('clients')
    # ### end Alembic commands ###
